apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.serviceTargetPort }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.serviceType }}