apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: {{ .Values.secrets.dbPassword }}
  rmq-pass: {{ .Values.secrets.rmqPassword }}
---
{{- if .Values.dockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}